"""empty message

Revision ID: 884a09ea0dfa
Revises: a9914aaa1792
Create Date: 2021-09-07 17:08:22.512940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884a09ea0dfa'
down_revision = 'a9914aaa1792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('importation', sa.String(length=32), nullable=False),
    sa.Column('types', sa.String(length=32), nullable=False),
    sa.Column('price1', sa.Integer(), nullable=False),
    sa.Column('price2', sa.Integer(), nullable=False),
    sa.Column('fuel_efficiency', sa.String(length=32), nullable=False),
    sa.Column('fuel', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Car')
    # ### end Alembic commands ###
